UNIT PREGUNTAS;

{$CODEPAGE UTF8}

INTERFACE

USES
  CRT, ARCHIVO;

PROCEDURE PREG_RESP (VAR ARCH:T_ARCHIVO);
PROCEDURE INICIALIZAR_PREGUNTAS (VAR REG:T_DATO2);

IMPLEMENTATION
PROCEDURE INICIALIZAR_PREGUNTAS (VAR REG:T_DATO2);
BEGIN
     REG.PREGUNTA:='';
     REG.RESPUESTA :='';
END;

PROCEDURE PREG_RESP (VAR ARCH:T_ARCHIVO);
VAR
  CREADO:BOOLEAN;
  REG:T_DATO2;
  POS:INTEGER;
BEGIN
     ABRIRBOT(ARCH);
                 REG.RESPUESTA := 'NUESTRA FACULTAD CUENTA CON LOS SIGUIENTES DEPORTES(FEMENINO Y MASCULINO): FUTBOL, VOLEY, BASKET, NATACION, PADEL, HOKEY, RUGBY, AJEDREZ. PARA MAS INFORMACION ACERCARSE A SAE';
                  REG.RESPUESTA:=UPCASE( REG.RESPUESTA);
                 POS:=0;
                 GUARDA_REGISTRO(ARCH,POS,REG);
                 REG.RESPUESTA := 'NUESTRA INSCRIPCION SE REALIZA A TRAVES DEL SIU GUARANI, DONDE ENCONTRARAN UN APARTADO DE INSCRIPCION A CURSADA. RECORDAR LA IMPORTANCIA DE LA ENCUENTAS';
                 REG.RESPUESTA:=UPCASE( REG.RESPUESTA);
                 POS:=1;
                 GUARDA_REGISTRO(ARCH,POS,REG);
                 REG.RESPUESTA := 'NUESTROS MAILS IMPORTANTES PUEDEN SER: SAE@FRCU.UTN.EDU.AR - DPTOALUM@FRCU.UTN.EDU.AR - ALUMNOS@FRCU.UTN.EDU.AR - DEPTOSISTEMAS@FRCU.UTN.EDU.AR - ASESORIAPEDAGOGICA@FRCU.UTN.EDU.AR - BIBLIOTECA@FRCU.UTN.EDU.AR - CURSADA@FRCU.UTN.EDU.AR - EXAMENES@FRCU.UTN.EDU.AR';
                 REG.RESPUESTA:=UPCASE( REG.RESPUESTA);
                 POS:=2;
                 GUARDA_REGISTRO(ARCH,POS,REG);
                 REG.RESPUESTA := 'PARA NUESTRAS AULAS IMPORTANTES TENDREMOS: SAE, CEICU, ALUMNOS, ENFERMERIA, SECRETARIA.';
                 REG.RESPUESTA:=UPCASE( REG.RESPUESTA);
                 POS:=3;
                 GUARDA_REGISTRO(ARCH,POS,REG);
                 REG.RESPUESTA := 'LA FACULTAD CUENTA CON BECAS DE SERVICIO Y/O INVESTIGACION. TAMBIEN PODEMOS ACCEDER A BECAS TALES COMO LA MANUEL BELGRANO O PROGRESAR. PARA MAS INFORMACION ACERCASE A SAE.';
                 REG.RESPUESTA:=UPCASE( REG.RESPUESTA);
                 POS:=4;
                 GUARDA_REGISTRO(ARCH,POS,REG);
          CLOSE(ARCH);
END;



END.