UNIT RESPUESTAS_MENU;

{$CODEPAGE UTF8}

INTERFACE

USES
  CRT, ARCHIVO, PREGUNTAS, VYP;

PROCEDURE INICIAR_ASISTENTE(VAR ARCH: T_ARCHIVO);
FUNCTION POSICION(VAR BUSCADOSUBCAD: STRING; BUSCADO: STRING): BYTE;
PROCEDURE FUNCIONAMIENTO();
PROCEDURE BUSQUEDA(VAR ARCH: T_ARCHIVO; BUSCADO: STRING; VAR POSI: INTEGER; VAR ENC: BOOLEAN);

IMPLEMENTATION

FUNCTION POSICION(VAR BUSCADOSUBCAD: STRING; BUSCADO: STRING): BYTE;
CONST
  SINONIMOS: ARRAY[1..33, 1..2] OF STRING = (
    ('BECAS', 'BECA'),
    ('BECA', 'BECA'),
    ('SUBVENCION', 'BECA'),
    ('SUBSIDIO', 'BECA'),
    ('SUBSIDIADO', 'BECA'),
    ('SUBSIDIAR', 'BECA'),
    ('DEPORTE', 'DEPORTE'),
    ('DEPORTES', 'DEPORTE'),
    ('DEPORTIVA', 'DEPORTE'),
    ('EJERCICIO', 'DEPORTE'),
    ('FISICA', 'DEPORTE'),
    ('AULA', 'AULA'),
    ('AULAS', 'AULA'),
    ('SALON', 'AULA'),
    ('SALONES', 'AULA'),
    ('CATEDRA', 'AULA'),
    ('CATEDRAS', 'AULA'),
    ('INSCRIPCION', 'INSCRIPCION'),
    ('INSCRIPCIONES', 'INSCRIPCION'),
    ('INSCRIBIRSE', 'INSCRIPCION'),
    ('INSCRIBIR', 'INSCRIPCION'),
    ('ANOTARSE', 'INSCRIPCION'),
    ('ANOTARME', 'INSCRIPCION'),
    ('ANOTAR', 'INSCRIPCION'),
    ('MATRICULAR', 'INSCRIPCION'),
    ('MATRICULARME', 'INSCRIPCION'),
    ('MATRICULARSE', 'INSCRIPCION'),
    ('MAIL', 'MAIL'),
    ('MAILS', 'MAIL'),
    ('CORREO', 'MAIL'),
    ('CORREOS', 'MAIL'),
    ('GMAIL', 'MAIL'),
    ('GMAILS', 'MAIL')
  );
VAR
  I: BYTE;
  ENCONTRADO: BOOLEAN;
BEGIN
  BUSCADO := UPCASE(BUSCADO);
  POSICION := 0;
  ENCONTRADO := FALSE;

  I := 1;
  WHILE (I <= 33) AND (NOT ENCONTRADO) DO
  BEGIN
    IF POS(SINONIMOS[I, 1], BUSCADO) > 0 THEN
    BEGIN
      BUSCADOSUBCAD := SINONIMOS[I, 2];
      POSICION := POS(SINONIMOS[I, 1], BUSCADO);
      ENCONTRADO := TRUE;
    END;
    INC(I);
  END;
END;

PROCEDURE BUSQUEDA(VAR ARCH: T_ARCHIVO; BUSCADO: STRING; VAR POSI: INTEGER; VAR ENC: BOOLEAN);
VAR
  X: T_DATO2;
  I: INTEGER;
BEGIN
  POSI := -1;
  ENC := FALSE;

  I := 0;
  WHILE (I < FILESIZE(ARCH)) AND (NOT ENC) DO
  BEGIN
    SEEK(ARCH, I);
    READ(ARCH, X);
    IF POS(BUSCADO, UPCASE(X.RESPUESTA)) > 0 THEN
    BEGIN
      ENC := TRUE;
      POSI := I;
    END;
    INC(I);
  END;
END;



PROCEDURE INICIAR_ASISTENTE(VAR ARCH: T_ARCHIVO);
VAR
  PREGUNTA, NOMBRE, SUBCAD_RESP: STRING;
  X: T_DATO2;
  ENC, SALIR: BOOLEAN;
  POSI: INTEGER;
BEGIN
  RESET(ARCH);
  TEXTCOLOR(YELLOW);
  gotoxy(36,23);
  WRITE('INGRESE SU NOMBRE: ');
  TEXTCOLOR(LIGHTBLUE);
  READLN(NOMBRE);
  while not ESCADENA(NOMBRE) DO
  BEGIN
    gotoxy(36,23);
    TEXTCOLOR(YELLOW);
    WRITE('INGRESE SU NOMBRE: ');
    TEXTCOLOR(LIGHTBLUE);
    READLN(NOMBRE);
    gotoxy(45,23);
    clreol;
  end;

  CLRSCR;


  TEXTCOLOR(WHITE);
  GOTOXY(61+length(nombre),2);
  WRITE(' !');
  GOTOXY(48,2);
  WRITE('¡ BIENVENIDO ');
  TEXTCOLOR(BLUE);
  WRITE(upcase(NOMBRE));
  GOTOXY(28,4);
  DELAY(500);
  ESCRIBIENDO();
  TEXTCOLOR(LIGHTBLUE);
  WRITELN;
  write('BOT: ');
  TEXTCOLOR(LIGHTGRAY);
  WRITE(SALUDO_RESP());
  WRITE('. Seré tu asistente virtual hoy, puedo ayudarte con temas vinculados a la UTN FRCU tales como BECAS, AULAS, INSCRIPCIONES, DEPORTE Y MAILS. Recorda que para cerrrarme solo basta con despedirte.');
  WRITELN();


  SALIR := FALSE;

  REPEAT
    TEXTCOLOR(YELLOW);
    GOTOXY(0,10);
    WRITE('YOU: ');
    TEXTCOLOR(WHITE);
    READLN(PREGUNTA);
    PREGUNTA := UPCASE(PREGUNTA);


    SALIR := (PREGUNTA = 'CHAU') OR (PREGUNTA = 'NOS VEMOS') OR (PREGUNTA = 'CIAO') OR
             (PREGUNTA = 'ADIOS') OR (PREGUNTA = 'HASTA LUEGO') OR (PREGUNTA = 'HASTA MAÑANA') OR
             (PREGUNTA = 'BYE');

    IF NOT SALIR THEN
    BEGIN

      IF (PREGUNTA = 'HOLA') OR (PREGUNTA = 'COMO ANDAS?') OR (PREGUNTA = 'TODO BIEN?') OR
         (PREGUNTA = 'BUEN DIA') OR (PREGUNTA = 'BUENAS TARDES') OR (PREGUNTA = 'BUENAS NOCHES') OR
         (PREGUNTA = 'HOLIS') OR (PREGUNTA = 'BUENAS') OR (PREGUNTA = 'BUENASS') OR
         (PREGUNTA = 'QUE SE CUENTA?') OR (PREGUNTA = 'QUE ONDA?') THEN
      BEGIN
        ESCRIBIENDO();
        DELAY(500);
        TEXTCOLOR(LIGHTBLUE);
        GOTOXY(0,WHEREY+1);
        write('BOT: ');
        TEXTCOLOR(LIGHTGRAY);
        WRITELN(SALUDO_RESP());
      END
      ELSE

      IF (PREGUNTA = 'GRACIAS') OR (PREGUNTA = 'MUCHAS GRACIAS') OR (PREGUNTA = 'MUY UTIL') OR
         (PREGUNTA = 'EXCELENTE') OR (PREGUNTA = 'SE AGRADECE') OR (PREGUNTA = 'MIL GRACIAS') OR
         (PREGUNTA = 'GRACIELA') OR (PREGUNTA = 'JOYA') OR (PREGUNTA = 'JOYITA') OR
         (PREGUNTA = 'MUY AMABLE') THEN
      BEGIN
        ESCRIBIENDO();
        DELAY(500);
        TEXTCOLOR(LIGHTBLUE);
        write('BOT: ');
        TEXTCOLOR(LIGHTGRAY);
        WRITELN(GRACIAS_RESP());
      END
      ELSE

      IF POSICION(SUBCAD_RESP, PREGUNTA) > 0 THEN
      BEGIN
        BUSQUEDA(ARCH, SUBCAD_RESP, POSI, ENC);
        IF ENC THEN
        BEGIN
          SEEK(ARCH, POSI);
          READ(ARCH, X);
          ESCRIBIENDO();
          DELAY(500);
          TEXTCOLOR(LIGHTBLUE);
          WRITE('BOT: ');
          TEXTCOLOR(LIGHTGRAY);
          WRITE(ELOGIO_RESP(), '. ');
          WRITELN(X.RESPUESTA);
        END
        ELSE
        BEGIN
          ESCRIBIENDO();
          DELAY(500);
          TEXTCOLOR(LIGHTBLUE);
          write('BOT: ');
          TEXTCOLOR(LIGHTGRAY);
          WRITELN(FALLO_RESP());
        END;
      END
      ELSE
      BEGIN
        ESCRIBIENDO();
        DELAY(500);
        TEXTCOLOR(LIGHTBLUE);
        write('BOT: ');
        TEXTCOLOR(LIGHTGRAY);
        WRITELN(FALLO_RESP());
      END;
    END;
  UNTIL SALIR;

  ESCRIBIENDO();
  DELAY(500);
  WRITELN(DESPEDIDA_RESP());
  DELAY(1500);
  PantallaCarga
END;





PROCEDURE FUNCIONAMIENTO ();
BEGIN
     CLRSCR;
     GOTOXY(35,5);
     TEXTCOLOR(LIGHTGREEN);
     WRITELN(' FUNCIONES DE NUESTRO ASISTENTE VIRTUAL ');
     GOTOXY(24,12);
     TEXTCOLOR(WHITE);
     GOTOXY(22,10);
     WRITELN('ESTE ASISTENTE VIRTUAL, ESTÁ DISEÑADO PARA DAR RESPUESTAS LÓGICAS DEPENDIENDO');
     GOTOXY(22,12);
     WRITELN('DE LA PREGUNTA INGRESADA POR EL USUARIO, CONTENIENDO LA INFORMACION SOLICITADA');
     GOTOXY(22,14);
     WRITELN('SOBRE LA UTN-FRCU.');
     GOTOXY(22,18);
     TEXTCOLOR(RED);
     WRITELN('LA INFORMACIÓN CONTENIDA EN ESTE CHATTERBOT FUE CONFECCIONADA POR ALUMNOS DE LA FACULTAD');
     GOTOXY(22,19);
     WRITE('Y OBTENIDA DE LA PAGINA OFICIAL:');
     TEXTCOLOR(BLUE);
     WRITE(' HTTPS://WWW.FRCU.UTN.EDU.AR/ ');
     TEXTCOLOR(YELLOW);
     GOTOXY(35,24);
     WRITE('<< PRESIONE [ENTER] PARA CONTINUAR >>');
     READKEY;
     CLRSCR;
END;

END.