UNIT RESPUESTAS_MENU;

{$CODEPAGE UTF8}

INTERFACE

USES
  CRT, ARCHIVO,PREGUNTAS,VyP;

PROCEDURE INICIAR_ASISTENTE (VAR ARCH:T_ARCHIVO);
FUNCTION POSICION(VAR BUSCADOSUBCAD: STRING; BUSCADO: STRING): BYTE;
PROCEDURE FUNCIONAMIENTO ();
FUNCTION FALLO_RESP (VAR RESP:STRING):STRING;
PROCEDURE BUSQUEDA(VAR ARCH:T_ARCHIVO; BUSCADO: STRING; VAR POSI: INTEGER; VAR ENC: BOOLEAN; VAR K: BYTE);

IMPLEMENTATION

FUNCTION FALLO_RESP (VAR RESP:STRING):STRING;
VAR
  NUM:BYTE;
BEGIN
     NUM := RANDOM(9);
     CASE NUM OF
     0: FALLO_RESP := 'LO SIENTO, VOLVAMOS A INTENTAR';
     1: FALLO_RESP := 'PERDÓN, VOLVAMOS A INTENTAR';
     2: FALLO_RESP := 'DISCULPA, VOLVAMOS A INTENTAR';
     3:  FALLO_RESP := 'LO LAMENTO, VOLVAMOS A INTENTAR';
     4:  FALLO_RESP := 'UPS ALGO SALIO MAL, VOLVAMOS A INTENTAR';
     5:  FALLO_RESP := 'OH NO!!!, VOLVAMOS A INTENTAR';
     6:  FALLO_RESP := 'ALGO FALLO, VOLVAMOS A INTENTAR';
     7: FALLO_RESP := 'NO NO CLAUDIA, ESTO SI ESTA VALIDADO';
     8: FALLO_RESP := 'NAO NAO MANITO';
     END;
END;


{FUNCTION POSICION(VAR BUSCADOSUBCAD: STRING; BUSCADO: STRING): BYTE;
TYPE
T_VECTOR=ARRAY [1..38] OF STRING;
VAR
V:T_VECTOR;
I:1..38;
BEGIN
V[1]:='AULA';
V[2]:='AULAS';
V[3]:='BECAS';
V[4]:='BECA';
V[5]:='CATEDRA';
V[6]:='CATEDRAS';
V[7]:='CORREO';
V[8]:='DEPORTE';
V[9]:='DEPORTES';
V[10]:='DEPORTIVAS';
V[11]:='EJERCICIO';
V[12]:='EJERCICIOS';
V[13]:='EJERCITAR';
V[14]:='EJERCITARME';
V[15]:='FISICA';
V[16]:='GIMNASIA';
V[17]:='GMAIL';
V[18]:='GMAILS';
V[19]:='INSCRIPCION';
V[20]:='INSCRIPCIONES';
V[21]:='INSCRIBIRME';
V[22]:='INSCRIBIRSE';
V[23]:='MAIL';
V[24]:='MAILS';
V[25]:='MATRICULAR';
V[26]:='MATRICULARME';
V[27]:='REGISTRAR';
V[28]:='REGISTRARME';
V[29]:='SALON';
V[30]:='SALONES';
V[31]:='SUBSIDIADO';
V[32]:='SUBSIDIAR';
V[33]:='SUBSIDIO';
V[34]:='SUBVENCIÓN';
V[35]:='ANOTARME';
V[36]:='ANOTARSE';
V[37]:='APUNTAR';
V[38]:='APUNTARME';

FOR I:=1 TO 38 DO
BEGIN
IF POS(V[I], BUSCADO) <> 0 THEN
BEGIN
POSICION:=POS(V[I], BUSCADO);
BUSCADOSUBCAD:=V[I];
END;
END;
END;    }

FUNCTION POSICION(VAR BUSCADOSUBCAD: STRING; BUSCADO: STRING): BYTE;
TYPE
  T_VECTOR = ARRAY [1..38] OF STRING;
VAR
  V: T_VECTOR;
  I: 1..38;
  Encontrado: BOOLEAN;
BEGIN
  V[1]:='AULA';
  V[2]:='AULAS';
  V[3]:='BECAS';
  V[4]:='BECA';
  V[5]:='CATEDRA';
  V[6]:='CATEDRAS';
  V[7]:='CORREO';
  V[8]:='DEPORTE';
  V[9]:='DEPORTES';
  V[10]:='DEPORTIVAS';
  V[11]:='EJERCICIO';
  V[12]:='EJERCICIOS';
  V[13]:='EJERCITAR';
  V[14]:='EJERCITARME';
  V[15]:='FISICA';
  V[16]:='GIMNASIA';
  V[17]:='GMAIL';
  V[18]:='GMAILS';
  V[19]:='INSCRIPCION';
  V[20]:='INSCRIPCIONES';
  V[21]:='INSCRIBIRME';
  V[22]:='INSCRIBIRSE';
  V[23]:='MAIL';
  V[24]:='MAILS';
  V[25]:='MATRICULAR';
  V[26]:='MATRICULARME';
  V[27]:='REGISTRAR';
  V[28]:='REGISTRARME';
  V[29]:='SALON';
  V[30]:='SALONES';
  V[31]:='SUBSIDIADO';
  V[32]:='SUBSIDIAR';
  V[33]:='SUBSIDIO';
  V[34]:='SUBVENCIÓN';
  V[35]:='ANOTARME';
  V[36]:='ANOTARSE';
  V[37]:='APUNTAR';
  V[38]:='APUNTARME';

  Encontrado := FALSE;
  POSICION := 0;  // Inicializamos la posición en 0

  // Convertimos BUSCADO y las palabras en V a mayúsculas para evitar problemas de mayúsculas/minúsculas
  BUSCADO := UpCase(BUSCADO);

  FOR I := 1 TO 38 DO
  BEGIN
    // Convertimos las palabras de V a mayúsculas para comparación consistente
    IF POS(UpCase(V[I]), BUSCADO) <> 0 THEN
    BEGIN
      BUSCADOSUBCAD := V[I];  // Si encontramos una coincidencia, asignamos la subcadena
      POSICION := POS(UpCase(V[I]), BUSCADO);  // Asignamos la posición de la coincidencia
      Encontrado := TRUE;  // Marcamos como encontrado
    END;
  END;

  IF NOT Encontrado THEN
    POSICION := 0;  // Si no se encontró ninguna coincidencia, dejamos la posición en 0
END;




{PROCEDURE BUSQUEDA(VAR ARCH:T_ARCHIVO;BUSCADO:STRING;VAR POSI:INTEGER;VAR ENC:BOOLEAN; VAR K:BYTE);
VAR
I:BYTE;
X:T_DATO2;
SUBCAD_RESP:STRING;
BEGIN
POSI:=-1;
I:=0;
ENC:=FALSE;
SUBCAD_RESP:='';
WHILE (I<FILESIZE(ARCH)) AND (NOT ENC) DO
BEGIN
SEEK(ARCH,I);
READ(ARCH,X);
IF POS(BUSCADO, X.RESPUESTA) <> 0 THEN
   BEGIN
         CASE BUSCADO OF
             'BECAS': SUBCAD_RESP:='BECA';
'SUBVENCIÓN': SUBCAD_RESP:='BECA';
'SUBSIDIO': SUBCAD_RESP:='BECA';
'SUBSIDIADO': SUBCAD_RESP:='BECA';
'SUBSIDIAR': SUBCAD_RESP:='BECA';

'DEPORTE': SUBCAD_RESP:='DEPORTE';
'DEPORTES': SUBCAD_RESP:='DEPORTE';
'DEPORTIVAS': SUBCAD_RESP:='DEPORTE';
'FISICA': SUBCAD_RESP:='DEPORTE';
'EJERCICIO': SUBCAD_RESP:='DEPORTE';
'EJERCICIOS': SUBCAD_RESP:='DEPORTE';
'EJERCITAR': SUBCAD_RESP:='DEPORTE';
'EJERCITARME': SUBCAD_RESP:='DEPORTE';
'GIMNASIA': SUBCAD_RESP:='DEPORTE';

'AULA': SUBCAD_RESP:='AULA';
'AULAS': SUBCAD_RESP:='AULA';
'SALON': SUBCAD_RESP:='AULA';
'SALONES': SUBCAD_RESP:='AULA';
'CATEDRA': SUBCAD_RESP:='AULA';
'CATEDRAS': SUBCAD_RESP:='AULA';

'INSCRIPCIONES': SUBCAD_RESP:='INSCRIPCION';
'INSCRIBIRSE': SUBCAD_RESP:='INSCRIPCION';
'INSCRIBIRME': SUBCAD_RESP:='INSCRIPCION';
'ANOTARSE': SUBCAD_RESP:='INSCRIPCION';
'ANOTARME': SUBCAD_RESP:='INSCRIPCION';
'INSCRIPCION': SUBCAD_RESP:='INSCRIPCION';
'APUNTAR': SUBCAD_RESP:='INSCRIPCION';
'APUNTARME': SUBCAD_RESP:='INSCRIPCION';
'REGRISTRAR': SUBCAD_RESP:='INSCRIPCION';
'REGRISTRARME': SUBCAD_RESP:='INSCRIPCION';
'MATRICULAR': SUBCAD_RESP:='INSCRIPCION';
'MATRICULARME': SUBCAD_RESP:='INSCRIPCION';

'MAIL': SUBCAD_RESP:='MAIL';
'MAILS': SUBCAD_RESP:='MAIL';
'GMAIL': SUBCAD_RESP:='MAIL';
'GMAILS': SUBCAD_RESP:='MAIL';
'CORREO': SUBCAD_RESP:='MAIL';
         END;
    END;
IF BUSCADO = SUBCAD_RESP THEN
BEGIN
     ENC:=TRUE;
     POSI:=I;
     END
ELSE
BEGIN
I:=I+1;
END;
END;
END;  }

PROCEDURE BUSQUEDA(VAR ARCH:T_ARCHIVO; BUSCADO: STRING; VAR POSI: INTEGER; VAR ENC: BOOLEAN; VAR K: BYTE);
VAR
  I: BYTE;
  X: T_DATO2;
  CATEGORIAS_ENCONTRADAS: STRING;
BEGIN
  POSI := -1;
  I := 0;
  ENC := FALSE;
  CATEGORIAS_ENCONTRADAS := '';  // Inicializamos una cadena para almacenar las categorías encontradas

  WHILE (I < FILESIZE(ARCH)) AND (NOT ENC) DO
  BEGIN
    SEEK(ARCH, I);
    READ(ARCH, X);

    // Revisamos si BUSCADO aparece dentro de la respuesta
    IF POS(BUSCADO, X.RESPUESTA) <> 0 THEN
    BEGIN
      // Revisamos si encontramos alguna de las categorías y la añadimos a CATEGORIAS_ENCONTRADAS
      IF (POS('BECAS', X.RESPUESTA) > 0) OR
         (POS('SUBVENCIÓN', X.RESPUESTA) > 0) OR
         (POS('SUBSIDIO', X.RESPUESTA) > 0) OR
         (POS('SUBSIDIADO', X.RESPUESTA) > 0) OR
         (POS('SUBSIDIAR', X.RESPUESTA) > 0) THEN
        CATEGORIAS_ENCONTRADAS := CATEGORIAS_ENCONTRADAS + ' BECA';  // Añadimos "BECA" a la cadena

      IF (POS('DEPORTE', X.RESPUESTA) > 0) OR
         (POS('DEPORTES', X.RESPUESTA) > 0) OR
         (POS('DEPORTIVAS', X.RESPUESTA) > 0) OR
         (POS('FISICA', X.RESPUESTA) > 0) OR
         (POS('EJERCICIO', X.RESPUESTA) > 0) OR
         (POS('EJERCICIOS', X.RESPUESTA) > 0) OR
         (POS('EJERCITAR', X.RESPUESTA) > 0) OR
         (POS('EJERCITARME', X.RESPUESTA) > 0) OR
         (POS('GIMNASIA', X.RESPUESTA) > 0) THEN
        CATEGORIAS_ENCONTRADAS := CATEGORIAS_ENCONTRADAS + ' DEPORTE';  // Añadimos "DEPORTE" a la cadena

      IF (POS('AULA', X.RESPUESTA) > 0) OR
         (POS('AULAS', X.RESPUESTA) > 0) OR
         (POS('SALON', X.RESPUESTA) > 0) OR
         (POS('SALONES', X.RESPUESTA) > 0) OR
         (POS('CATEDRA', X.RESPUESTA) > 0) OR
         (POS('CATEDRAS', X.RESPUESTA) > 0) THEN
        CATEGORIAS_ENCONTRADAS := CATEGORIAS_ENCONTRADAS + ' AULA';  // Añadimos "AULA" a la cadena

      IF (POS('INSCRIPCIONES', X.RESPUESTA) > 0) OR
         (POS('INSCRIBIRSE', X.RESPUESTA) > 0) OR
         (POS('INSCRIBIRME', X.RESPUESTA) > 0) OR
         (POS('ANOTARSE', X.RESPUESTA) > 0) OR
         (POS('ANOTARME', X.RESPUESTA) > 0) OR
         (POS('INSCRIPCION', X.RESPUESTA) > 0) OR
         (POS('APUNTAR', X.RESPUESTA) > 0) OR
         (POS('APUNTARME', X.RESPUESTA) > 0) OR
         (POS('REGRISTRAR', X.RESPUESTA) > 0) OR
         (POS('REGRISTRARME', X.RESPUESTA) > 0) OR
         (POS('MATRICULAR', X.RESPUESTA) > 0) OR
         (POS('MATRICULARME', X.RESPUESTA) > 0) THEN
        CATEGORIAS_ENCONTRADAS := CATEGORIAS_ENCONTRADAS + ' INSCRIPCION';  // Añadimos "INSCRIPCION" a la cadena

      IF (POS('MAIL', X.RESPUESTA) > 0) OR
         (POS('MAILS', X.RESPUESTA) > 0) OR
         (POS('GMAIL', X.RESPUESTA) > 0) OR
         (POS('GMAILS', X.RESPUESTA) > 0) OR
         (POS('CORREO', X.RESPUESTA) > 0) THEN
        CATEGORIAS_ENCONTRADAS := CATEGORIAS_ENCONTRADAS + ' MAIL';  // Añadimos "MAIL" a la cadena
    END;

    // Verificamos si la categoría concatenada contiene BUSCADO
    IF POS(BUSCADO, CATEGORIAS_ENCONTRADAS) <> 0 THEN
    BEGIN
      ENC := TRUE;
      POSI := I;
    END
    ELSE
    BEGIN
      I := I + 1;
    END;
  END;
END;



{PROCEDURE INICIAR_ASISTENTE (VAR ARCH:T_ARCHIVO);
VAR
PREGUNTA,NOMBRE:STRING[50];
SUBCAD_RESP,BUSCADO,RESP:STRING;
X:T_DATO2;
ENC:BOOLEAN;
POSI:INTEGER;
I:BYTE;
BEGIN
     ABRIRBOT(ARCH);
     CAJA(37,1,73,3);
     TEXTCOLOR(YELLOW);
     GOTOXY(48,2);
     WRITELN('ASISTENTE VIRTUAL');
     GOTOXY(1,5);
     WRITE('INGRESE SU NOMBRE:');
     WRITELN();
     TEXTCOLOR(BLUE);
     WRITE('-');
     READLN(NOMBRE);
     WRITELN();
     TEXTCOLOR(YELLOW);
     CLRSCR;
      CAJA(37,1,73,3);
     TEXTCOLOR(YELLOW);
     GOTOXY(48,2);
     WRITELN('ASISTENTE VIRTUAL');
      GOTOXY(1,5);
     WRITE('BIENVENIDO ');
     TEXTCOLOR(BLUE);
     WRITE(NOMBRE);
     TEXTCOLOR(YELLOW);
     WRITELN();
     WRITELN('HOY SERE TU ASISTENTE Y PUEDO OFRECERTE INFORMACION ACERCA:');
     GOTOXY(40,10);
     WRITELN('  DEPORTES ');
     GOTOXY(40,10);
     TEXTCOLOR(BLUE);
     WRITE('*');
     GOTOXY(40,12);
     TEXTCOLOR(YELLOW);
     WRITELN('  BECAS');
     GOTOXY(40,12);
     TEXTCOLOR(BLUE);
     WRITE('*');
     GOTOXY(40,14);
      TEXTCOLOR(YELLOW);
     WRITELN('  AULAS UTILES');
     GOTOXY(40,14);
     TEXTCOLOR(BLUE);
     WRITE('*');
     GOTOXY(40,16);
      TEXTCOLOR(YELLOW);
     WRITELN('  INSCRIPCIONES A MATERIAS');
     GOTOXY(40,16);
     TEXTCOLOR(BLUE);
     WRITE('*');
     GOTOXY(40,18);
      TEXTCOLOR(YELLOW);
     WRITELN('  MAILS IMPORTANTES ');
     GOTOXY(40,18);
     TEXTCOLOR(BLUE);
     WRITE('*');
     GOTOXY(1,22);
     TEXTCOLOR(YELLOW);
     WRITE('INGRESE SU CONSULTA');
     TEXTCOLOR(RED);
     WRITE('  << PRESIONE 0 PARA SALIR >> ');
     TEXTCOLOR(CYAN);
     WRITELN();
     WRITE(' - ');
    READLN(PREGUNTA);
     PREGUNTA:= UPCASE(PREGUNTA);
     REPEAT
           IF PREGUNTA <> '0' THEN
           BEGIN
           IF POSICION(SUBCAD_RESP, PREGUNTA) > 0 THEN
           BEGIN
           CASE SUBCAD_RESP OF
           'BECAS': SUBCAD_RESP:='BECA';
'SUBVENCIÓN': SUBCAD_RESP:='BECA';
'SUBSIDIO': SUBCAD_RESP:='BECA';
'SUBSIDIADO': SUBCAD_RESP:='BECA';
'SUBSIDIAR': SUBCAD_RESP:='BECA';

'DEPORTE': SUBCAD_RESP:='DEPORTE';
'DEPORTES': SUBCAD_RESP:='DEPORTE';
'DEPORTIVAS': SUBCAD_RESP:='DEPORTE';
'FISICA': SUBCAD_RESP:='DEPORTE';
'EJERCICIO': SUBCAD_RESP:='DEPORTE';
'EJERCICIOS': SUBCAD_RESP:='DEPORTE';
'EJERCITAR': SUBCAD_RESP:='DEPORTE';
'EJERCITARME': SUBCAD_RESP:='DEPORTE';
'GIMNASIA': SUBCAD_RESP:='DEPORTE';

'AULA': SUBCAD_RESP:='AULA';
'AULAS': SUBCAD_RESP:='AULA';
'SALON': SUBCAD_RESP:='AULA';
'SALONES': SUBCAD_RESP:='AULA';
'CATEDRA': SUBCAD_RESP:='AULA';
'CATEDRAS': SUBCAD_RESP:='AULA';

'INSCRIPCIONES': SUBCAD_RESP:='INSCRIPCION';
'INSCRIBIRSE': SUBCAD_RESP:='INSCRIPCION';
'INSCRIBIRME': SUBCAD_RESP:='INSCRIPCION';
'ANOTARSE': SUBCAD_RESP:='INSCRIPCION';
'ANOTARME': SUBCAD_RESP:='INSCRIPCION';
'INSCRIPCION': SUBCAD_RESP:='INSCRIPCION';
'APUNTAR': SUBCAD_RESP:='INSCRIPCION';
'APUNTARME': SUBCAD_RESP:='INSCRIPCION';
'REGRISTRAR': SUBCAD_RESP:='INSCRIPCION';
'REGRISTRARME': SUBCAD_RESP:='INSCRIPCION';
'MATRICULAR': SUBCAD_RESP:='INSCRIPCION';
'MATRICULARME': SUBCAD_RESP:='INSCRIPCION';

'MAIL': SUBCAD_RESP:='MAIL';
'MAILS': SUBCAD_RESP:='MAIL';
'GMAIL': SUBCAD_RESP:='MAIL';
'GMAILS': SUBCAD_RESP:='MAIL';
'CORREO': SUBCAD_RESP:='MAIL';

END;

BUSQUEDA(ARCH,SUBCAD_RESP,POSI,ENC,I);

IF ENC = TRUE THEN
BEGIN
  CLRSCR;
  CAJA(37,1,73,3);
  TEXTCOLOR(YELLOW);
  GOTOXY(48,2);
  WRITELN('ASISTENTE VIRTUAL');
  GOTOXY(2,4);
  TEXTCOLOR(BLUE);

  // Verificamos que POSI sea válido antes de hacer SEEK
  IF (POSI >= 0) AND (POSI < FILESIZE(ARCH)) THEN
  BEGIN
    SEEK(ARCH, POSI);
    READ(ARCH, X);
    WRITELN(' EXCELENTE, SOBRE ', SUBCAD_RESP, ' PUEDO CONTARTE QUE: ');
    TEXTCOLOR(YELLOW);
    GOTOXY(2,6);
    WRITELN(X.RESPUESTA);
  END
  ELSE
  BEGIN
    WRITELN('ERROR: No se encontró una respuesta válida.');
  END;

  GOTOXY(60,10);
  TEXTCOLOR(RED);
  WRITELN(' << PRESIONE [ENTER] PARA CONTINUAR >> ');
  READKEY;
  CLRSCR;
END;

            END;
            END
            ELSE
            BEGIN
            CLRSCR;
            TEXTCOLOR(BLUE);
            WRITELN( FALLO_RESP(RESP));
            END;
           TEXTCOLOR(BLUE);
           WRITE('POR FAVOR INGRESE SU PREGUNTA');
           TEXTCOLOR(RED);
           WRITELN(' U << OPRIMA 0 PARA SALIR >>');
           WRITE(' - ');
           TEXTCOLOR(CYAN);
           READLN(PREGUNTA);
           PREGUNTA:= UPCASE(PREGUNTA);
           END;
     UNTIL PREGUNTA='0' ;
     //CLOSE(ARCH);
END;                   }


PROCEDURE INICIAR_ASISTENTE (VAR ARCH:T_ARCHIVO);
VAR
  PREGUNTA, NOMBRE: STRING[50];
  SUBCAD_RESP, BUSCADO, RESP: STRING;
  X: T_DATO2;
  ENC: BOOLEAN;
  POSI: INTEGER;
  I: BYTE;
BEGIN
  ABRIRBOT(ARCH);
  CAJA(37,1,73,3);
  TEXTCOLOR(YELLOW);
  GOTOXY(48,2);
  WRITELN('ASISTENTE VIRTUAL');
  GOTOXY(1,5);
  WRITE('INGRESE SU NOMBRE:');
  WRITELN();
  TEXTCOLOR(BLUE);
  WRITE('-');
  READLN(NOMBRE);
  WRITELN();
  TEXTCOLOR(YELLOW);
  CLRSCR;
  CAJA(37,1,73,3);
  TEXTCOLOR(YELLOW);
  GOTOXY(48,2);
  WRITELN('ASISTENTE VIRTUAL');
  GOTOXY(1,5);
  WRITE('BIENVENIDO ');
  TEXTCOLOR(BLUE);
  WRITE(NOMBRE);
  TEXTCOLOR(YELLOW);
  WRITELN();
  WRITELN('HOY SERE TU ASISTENTE Y PUEDO OFRECERTE INFORMACION ACERCA:');
  GOTOXY(40,10);
  WRITELN('  DEPORTES ');
  GOTOXY(40,10);
  TEXTCOLOR(BLUE);
  WRITE('*');
  GOTOXY(40,12);
  TEXTCOLOR(YELLOW);
  WRITELN('  BECAS');
  GOTOXY(40,12);
  TEXTCOLOR(BLUE);
  WRITE('*');
  GOTOXY(40,14);
  TEXTCOLOR(YELLOW);
  WRITELN('  AULAS UTILES');
  GOTOXY(40,14);
  TEXTCOLOR(BLUE);
  WRITE('*');
  GOTOXY(40,16);
  TEXTCOLOR(YELLOW);
  WRITELN('  INSCRIPCIONES A MATERIAS');
  GOTOXY(40,16);
  TEXTCOLOR(BLUE);
  WRITE('*');
  GOTOXY(40,18);
  TEXTCOLOR(YELLOW);
  WRITELN('  MAILS IMPORTANTES ');
  GOTOXY(40,18);
  TEXTCOLOR(BLUE);
  WRITE('*');
  GOTOXY(1,22);
  TEXTCOLOR(YELLOW);
  WRITE('INGRESE SU CONSULTA');
  TEXTCOLOR(RED);
  WRITE('  << PRESIONE 0 PARA SALIR >> ');
  TEXTCOLOR(CYAN);
  WRITELN();
  WRITE(' - ');
  READLN(PREGUNTA);
  PREGUNTA := UPCASE(PREGUNTA);
  REPEAT
    IF PREGUNTA <> '0' THEN
    BEGIN
      IF POSICION(SUBCAD_RESP, PREGUNTA) > 0 THEN
      BEGIN
        CASE SUBCAD_RESP OF
          // Las asignaciones de SUBCAD_RESP a partir del caso ...
          'BECAS': SUBCAD_RESP := 'BECA';
          // Otros casos de 'BECAS', 'DEPORTE', etc.
        END;
        BUSQUEDA(ARCH, SUBCAD_RESP, POSI, ENC, I);
        IF ENC = TRUE THEN
        BEGIN
          IF POSI >= 0 THEN  // Verificamos que POSI sea un valor válido
          BEGIN
            CLRSCR;
            CAJA(37,1,73,3);
            TEXTCOLOR(YELLOW);
            GOTOXY(48,2);
            WRITELN('ASISTENTE VIRTUAL');
            GOTOXY(2,4);
            TEXTCOLOR(BLUE);
            SEEK(ARCH, POSI);
            READ(ARCH, X);
            WRITELN(' EXCELENTE, SOBRE ', SUBCAD_RESP, ' PUEDO CONTARTE QUE: ');
            TEXTCOLOR(YELLOW);
            GOTOXY(2,6);
            WRITELN(X.RESPUESTA);
            GOTOXY(60,10);
            TEXTCOLOR(RED);
            WRITELN(' << PRESIONE [ENTER] PARA CONTINUAR >> ');
            READKEY;
            CLRSCR;
          END
          ELSE
          BEGIN
            CLRSCR;
            TEXTCOLOR(BLUE);
            WRITELN( FALLO_RESP(RESP));
          END;
        END;
      END
      ELSE
      BEGIN
        CLRSCR;
        TEXTCOLOR(BLUE);
        WRITELN( FALLO_RESP(RESP));
      END;
      TEXTCOLOR(BLUE);
      WRITE('POR FAVOR INGRESE SU PREGUNTA');
      TEXTCOLOR(RED);
      WRITELN(' U << OPRIMA 0 PARA SALIR >>');
      WRITE(' - ');
      TEXTCOLOR(CYAN);
      READLN(PREGUNTA);
      PREGUNTA := UPCASE(PREGUNTA);
    END;
  UNTIL PREGUNTA = '0';
END;




PROCEDURE FUNCIONAMIENTO ();
BEGIN
     CLRSCR;
     GOTOXY(35,5);
     TEXTCOLOR(YELLOW);
     WRITELN(' FUNCION DE NUESTRO ASISTENTE VIRTUAL ');
     GOTOXY(24,12);
     TEXTCOLOR(WHITE);
     GOTOXY(22,10);
     WRITELN('ESTE ASISTENTE VIRTUAL, ESTÁ DISEÑADO PARA DAR RESPUESTAS LÓGICAS DEPENDIENDO');
     GOTOXY(22,12);
     WRITELN('DE LA PREGUNTA INGRESADA POR EL USUARIO, CONTENIENDO LA INFORMACION SOLICITADA');
     GOTOXY(22,14);
     WRITELN('SOBRE LA UTN-FRCU.');
     GOTOXY(22,18);
     TEXTCOLOR(RED);
     WRITELN('LA INFORMACIÓN CONTENIDA EN ESTE CHATTERBOT FUE CONFECCIONADA POR ALUMNOS DE LA FACULTAD');
     GOTOXY(22,19);
     WRITE('Y OBTENIDA DE LA PAGINA OFICIAL:');
     TEXTCOLOR(BLUE);
     WRITE(' HTTPS://WWW.FRCU.UTN.EDU.AR/ ');
     TEXTCOLOR(YELLOW);
     GOTOXY(35,24);
     WRITE('<< PRESIONE [ENTER] PARA CONTINUAR >>');
     READKEY;
     CLRSCR;
END;

END.
